title: Diomedron # your site title
author: GitHub User
email: your-email@domain.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/diomed" # the subpath of your site, e.g. /blog
url: "https://rdyar.github.io/diomed/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: # # replace with your_twitter_username or comment to remove link from footer
github_username:  diomed # replace with your_github_username or comment to remove link from footer
instagram_username: # # replace with your_instagram_username or comment to remove link from footer
social:
  name: Catsuomahe Daihatsu
  links:
    - https://twitter.com/
    - https://github.com/diomed

disqus:
  shortname:  # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null

remote_theme: mmistakes/minimal-mistakes

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
 
